---

- name: "Install nginx"
  when: ansible_os_family == 'Debian'
  apt:
    name=nginx
    state=present

- name: "Install nginx"
  when: ansible_os_family == 'RedHat'
  yum:
    name=nginx
    state=present

- name: "Enable selinux boolean httpd_can_network_connect"
  when: ansible_selinux and ansible_selinux.status == 'enabled'
  seboolean: name=httpd_can_network_connect state=yes persistent=yes

- name: "Start nginx and set systemd to start it on boot"
  systemd:
    name: nginx
    state: started
    enabled: yes

